services:
  postgres:
    image: postgres:15
    container_name: auth_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  booking-postgres:
    image: postgres:15
    container_name: booking_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking_service
    ports:
      - "5434:5432"
    volumes:
      - booking_postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  booking_postgres_data:
